name: Backend CI

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies
      run:  pipenv install --dev

    - name: Run linter
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run linter
      run: pipenv run test
  
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t backend .