name: Node.js CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Pipenv
      run: sudo pip install pipenv
    
    - name: Lock dependencies
      run: sudo pipenv lock

    - name: Install dependencies
      run: sudo pipenv install --dev

    - name: Run linter
      run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Pipenv
      run: sudo pip install pipenv

    - name: Lock dependencies
      run: sudo pipenv lock

    - name: Install dependencies
      run: sudo pipenv install --dev

    - name: Run linter
      run: pipenv run test
  
  # runs only if lint and test jobs pass
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: starter/backend
    if: ${{ github.event.action }} == 'push'
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Pipenv
      run: sudo pip install pipenv

    - name: Lock dependencies
      run: sudo pipenv lock

    - name: Install dependencies
      run: sudo pipenv install --dev

    - name: Build Docker image
      run: |
        docker build -t backend .