name: Node.js CI

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install
    - name: List files in the repository
      run: ls -R

    - name: Run linter
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install
    - name: List files in the repository
      run: pwd

    - name: Run tests
      run: npm run test
  
  # runs only if lint and test jobs pass
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    if: ${{ github.event.action }} == 'push'
    
    steps:
    - id: ecr-publish
      name: Build image and publish to ECR
      uses: bitovi/github-actions-ecr-publish@v0.1.0
      with:
        checkout: false,
        use_sha: true
        aws_ecr_repo_name: frontend
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        registry: ${{ env.REGISTRY }}
        repo: ${{ env.REGISTRY_REPO }}
        region: ${{ env.AWS_REGION }}